### ISSUE TITLE
Can't show big gif files(3.24MB)

### ISSUE THREAD

**Issue by MiyamuraMiyako** [XamlAnimatedGif/XamlAnimatedGif#110]
Enviroument: WPF .Net4.0 Full
OS: Windows7 sp1 x86 and Windows 10 pro x64.
Behaviors: gif:AnimationBehavior.SourceUri="pack://siteoforigin:,,,/Images/inputcard.gif" gif:AnimationBehavior.AnimateInDesignMode="True" gif:AnimationBehavior.AutoStart="True" gif:AnimationBehavior.RepeatBehavior="Forever"
- big gif file cannot show.

[inputcard.zip](https://github.com/XamlAnimatedGif/XamlAnimatedGif/files/1442878/inputcard.zip)

**Comment by thomaslevesque** [comment]
It works for me in the demo app... It takes a while to load because it's so big, but it eventually shows up, although the animation is quite slow. The GIF doesn't seem to be optimized at all; passing it through a GIF optimizer makes it 10 times smaller, and then it loads faster and the animation is smoother.

Anyway, for very large animations, you should use a video rather than a GIF.

**Comment by MiyamuraMiyako** [comment]
Thank you for reply, I will optimize gif file makes it small.
