### ISSUE TITLE
AnimationBehavior.SetSourceUri does not work with relative path

### ISSUE THREAD

**Issue by fpskcd** [XamlAnimatedGif/XamlAnimatedGif#113]
- Application type: WPF 4.0
- Operating system version: Windows 10
- Expected behavior: When you call AnimationBehavior.SetSourceUri with a relative GIF file URI (i.e. file name only) and then call SetAutoStart, the specified image should display.
- Actual behavior: The image appears blank, even if UriKind.Relative or UriKind.RelativeOrAbsolute is specified in the Uri instance.

**Comment by fpskcd** [comment]
Yes, the Error event is raised. Is this by design?

**Comment by thomaslevesque** [comment]
> Yes, the Error event is raised. 

What is the error in the event args?

> Is this by design?

Not really by design; it's just that I can't guess the absolute URI from the relative URI if I don't have a base URI.

**Comment by fpskcd** [comment]
The error message is "Cannot locate resource 'nesting.gif'."
However, the "nesting.gif" file is in the same directory as the executable.

Here is the source code where the Error is raised:
TempURI = New Uri("Nesting.gif", UriKind.Relative)
AnimationBehavior.SetSourceUri(AnimationMedia, TempURI)


How do I read the baseUri for the image?

**Comment by thomaslevesque** [comment]
Ah, it's not the error I was expecting, so it might not be related to the use of a relative URI.

I'll try to reproduce the issue on my side. In the meantime, if the image is in a file, you can try to specify its full path, e.g. `new Uri(Path.GetFullPath("nesting.gif"))`

**Comment by thomaslevesque** [comment]
> The error message is "Cannot locate resource 'nesting.gif'."

Are you sure this is the exact message? This message doesn't exist in XamlAnimatedGif,.
When I tried, I got this instead: "Cannot find file with the specified URI"

Basically, this is because when you pass a relative URI, it is resolved based on the `Image` control's `BaseUri` (accessible via `((IUriContext)image).BaseUri`), which is something like `pack://application:,,,/WpfApp1;component/`, i.e. a resource URI. So, basically, the behavior is the same as when you write `<Image Source="nesting.gif" />` : WPF looks for the image in the app's resources, **not** in a file. So you should either include the image as a resource (by setting the Build Action to "Resource") or pass an absolute file URI (something like `file:///.../nesting.gif`; passing the absolute path to the `Uri` constructor will take care of converting to the proper format)

**Comment by fpskcd** [comment]
I understand now. Thank you for the clarification. I created the Image control in XAML, so I think that's the reason. I'll close the case for now.
