### ISSUE TITLE
It doesn't work when it set build action 'content'

### ISSUE THREAD

**Issue by tklee-dev** [XamlAnimatedGif/XamlAnimatedGif#134]
- Application type: WPF 4.5+ 
- Operating system version: win10
- Expected behavior:
- Actual behavior:
- Steps to reproduce the problem:
  1. Set gif file build action 'resource' it  works. 
  2. Set gif file build action 'content' it doesn't work. 
 
    <Image gif:AnimationBehavior.SourceUri="Gif/Main_A1.gif"/>

**Comment by tklee-dev** [comment]
it works.
path like below:
<Image gif:AnimationBehavior.SourceUri="pack://siteoforigin:,,,/ImageResource/Main_A1.gif"/>

**Comment by thomaslevesque** [comment]
Glad you were able to resolve the issue, @tklee-dev.
In fact, the problem isn't related to XamlAnimatedGif; it would have been the same issue with a normal image.

**Comment by HosseinTaarofi** [comment]
> it works.
> path like below:
> 
> ```
> <Image gif:AnimationBehavior.SourceUri="pack://siteoforigin:,,,/ImageResource/Main_A1.gif"/>
> ```

What should I use instead of the word siteoforigin?
Because it does not work when I use your code
This is my code now
            <Image x:Name="ImgLoading"  gif:AnimationBehavior.SourceUri="pack://siteoforigin:,,,/ImageResource/Loading.gif"   Height="180" Width="180" Visibility="Visible"    ></Image>

**Comment by HosseinTaarofi** [comment]
> it works.
> path like below:
> 
> ```
> <Image gif:AnimationBehavior.SourceUri="pack://siteoforigin:,,,/ImageResource/Main_A1.gif"/>
> ```

What should I use instead of the word siteoforigin?
Because it does not work when I use your code
This is my code now

`            <Image x:Name="ImgLoading"  gif:AnimationBehavior.SourceUri="pack://siteoforigin:,,,/ImageResource/Loading.gif"   Height="180" Width="180" Visibility="Visible"    ></Image>
`

**Comment by thomaslevesque** [comment]
@HosseinTaarofi what is the build action for your image? (in the Properties window)
If it's `Content`, use `siteoforigin`
If it's `Resource`, no need to specify the full URL, you can specify the path like this: "ImageResource/Loading.gif"
If it's something else, change it, because it won't work...
My advice is to use Resource, as it's the simplest to use, and it's embedded in the application binaries.

**Comment by HosseinTaarofi** [comment]
> build action

I want to specify the image path through C # code, not xaml, my problem is that my image path has to be dynamic and change according to different conditions.
My profile is as follows:
I use wpf
My build action is set to content
my OS is win 10 64bit
and my code is
`            string path = Utilities.GetCurrentPath() + "/Images/Venus/epp.gif";
            if (Configuration.Transaction.HostUri.Contains("Balance"))
                path = @"C:\Users\h.taarofi\Desktop\1456114_d103c.gif";
            else if (Configuration.Transaction.HostUri.Contains("billverify"))
                path = Utilities.GetCurrentPath() + "Images\\GiftCard\\paymentsbilling.gif";
            if (File.Exists(path))
            {
                var uri1 = new Uri(path);
                XamlAnimatedGif.AnimationBehavior.SetSourceUri(ImgLoading, uri1);
            }
`

**Comment by HosseinTaarofi** [comment]
> @HosseinTaarofi what is the build action for your image? (in the Properties window)
> If it's `Content`, use `siteoforigin`
> If it's `Resource`, no need to specify the full URL, you can specify the path like this: "ImageResource/Loading.gif"
> If it's something else, change it, because it won't work...
> My advice is to use Resource, as it's the simplest to use, and it's embedded in the application binaries.

I want to specify the image path through C # code, not xaml, my problem is that my image path has to be dynamic and change according to different conditions.
My profile is as follows:
I use wpf
My build action is set to content
My os is win10 64bit
and my code is :

            string path = Utilities.GetCurrentPath() + "/Images/Venus/epp.gif";
            if (Configuration.Transaction.HostUri.Contains("Balance"))
                path = @"C:\Users\h.taarofi\Desktop\1456114_d103c.gif";
            else if (Configuration.Transaction.HostUri.Contains("billverify"))
                path = Utilities.GetCurrentPath() + "Images\\GiftCard\\paymentsbilling.gif";
            if (File.Exists(path))
            {
                var uri1 = new Uri(path);
                XamlAnimatedGif.AnimationBehavior.SetSourceUri(ImgLoading, uri1);
            }

**Comment by HosseinTaarofi** [comment]
If possible, send a routing sample according to my code

**Comment by HosseinTaarofi** [comment]
And let me add this
In this case, the build operation must be set to Resource, otherwise the image will not be displayed
And the main point is that when it is displayed in Resource mode, the first period of the file is not displayed and the display of the file starts from the second period, in fact, the display of the image is delayed.

**Comment by HosseinTaarofi** [comment]
And let me add this
In this case, the build operation must be set to Resource, otherwise the image will not be displayed
And the main thing is that when displayed in Resource mode, the first file frames are not displayed, in fact, the image is displayed with a delay.

**Comment by thomaslevesque** [comment]
You don't need `siteoforigin` if you just specify an absolute path for the image. It should just work, assuming the file actually exists. Have you checked with the debugger if you're actually entering the `if (File.Exists(path))`?

Anyway, you really shouldn't do this... if you specify an absolute path to a file that's not part of the application files, it won't work anywhere except on your own machine, since other machines won't have that file.

> In this case, the build operation must be set to Resource, otherwise the image will not be displayed

Your path must be wrong, then. It works fine with an absolute file path, as shown in the demo app.

> And the main thing is that when displayed in Resource mode, the first file frames are not displayed,

I haven't seen that before. I can investigate if you provide a full repro.

> in fact, the image is displayed with a delay.

This is to be expected, especially if the GIF is very large. This is because the image is loaded asynchronously, to avoid freezing your app while the image is loaded.

**Comment by HosseinTaarofi** [comment]
Thank you very much for your tips and quick response
My problem was solved
