### ISSUE TITLE
Customize the Temporary File Path for GIF

### ISSUE THREAD

**Issue by Taiizor** [XamlAnimatedGif/XamlAnimatedGif#196]
I want to customize the temporary file location where GIFs are saved when an online GIF path is entered.

In short, Path.GetTempPath() is used by default. We should be able to customize this.

**Comment by thomaslevesque** [comment]
Hi @Taiizor,

Thanks for the feedback!
I'm not against the idea, but what is the rationale for this? Why is `%TEMP%` not an appropriate location for your use case?

**Comment by Taiizor** [comment]
> Hi @Taiizor,
> 
> Thanks for the feedback! I'm not against the idea, but what is the rationale for this? Why is `%TEMP%` not an appropriate location for your use case?

Actually, it's suitable, but my application has a Cache directory, and I don't want my application to create a temporary file in another location. Therefore, it would be better if we could customize the temporary location ourselves.

**Comment by thomaslevesque** [comment]
Ah, I see. I guess that would be possible.

Just not sure what the best way to expose the feature would be. Most of the library's API is through the `AnimationBehavior` class, with attached properties set through XAML. But an attached property wouldn't be appropriate here, since you typically want to set the cache directory globally.
Exposing this on `UriLoader` would make sense, but the class is internal, and I'd rather not expose it just for this.
Maybe just a static method on `AnimationBehavior`, that you would call when the app starts?
e.g. `AnimationBehavior.SetDownloadCacheLocation(@"C:\my\custom\path")`

Would you be willing to submit a PR for this?

**Comment by thomaslevesque** [comment]
> In the changes made, briefly, `AnimationBehavior.SetDownloadCacheLocation(imgComponent, @"C:\my\custom\path")` now changes the temporary file directory of the selected image component.

That's not what I had in mind. I don't think it's useful to be able to specify a different path for each image control. It's almost certainly overkill, and just adds complexity. That's what I said "an attached property wouldn't be appropriate" in my previous message 😉. I think it should just be a static field, shared by the whole app.

> Additionally, I added support for .NET 6, .NET 7, and .NET 8.

No, you didn't, because they were already supported 😉. An assembly targeting .NET 5.0 can be consumed by an app targeting any version >= .NET 5.0.

I know you meant well, and I appreciate it, but please refrain from making more changes than what has been discussed.

**Comment by Taiizor** [comment]
> > In the changes made, briefly, `AnimationBehavior.SetDownloadCacheLocation(imgComponent, @"C:\my\custom\path")` now changes the temporary file directory of the selected image component.
> 
> That's not what I had in mind. I don't think it's useful to be able to specify a different path for each image control. It's almost certainly overkill, and just adds complexity. That's what I said "an attached property wouldn't be appropriate" in my previous message 😉. I think it should just be a static field, shared by the whole app.
> 
> > Additionally, I added support for .NET 6, .NET 7, and .NET 8.
> 
> No, you didn't, because they were already supported 😉. An assembly targeting .NET 5.0 can be consumed by an app targeting any version >= .NET 5.0.
> 
> I know you meant well, and I appreciate it, but please refrain from making more changes than what has been discussed.

Actually, support for .NET Core 3.1 and .NET 5 has ended. I was planning to remove them and add .NET 6, 7, and 8, but I wanted to add them without removing them.

**Comment by thomaslevesque** [comment]
> Actually, support for .NET Core 3.1 and .NET 5 has ended. I was planning to remove them and add .NET 6, 7, and 8, but I wanted to add them without removing them.

Indeed. Usually I keep supporting older target frameworks as long as it's not painful to do so, but at some point I will remove .NET Core 3.1 and .NET 5. But I'll do this in a major release, since it's a breaking change.

**Comment by thomaslevesque** [comment]
I just published the new version, it should appear shortly on NuGet.
Thanks again for the contribution @Taiizor!
