### ISSUE TITLE
How to show image download progress?

### ISSUE THREAD

**Issue by EDiaos** [XamlAnimatedGif/XamlAnimatedGif#28]
Some time,our project need the image download progress at code. 
Can we add progress action to method,and we can use like this:

  _gifAnimation.InitAnimation(img, new Uri(...), (progress) =>
 {
       ShowProgress(progress);
})

**Comment by thomaslevesque** [comment]
The ability to download images automatically was only added as an afterthought, and I still think it's a bit out of scope for this project. So I'm reluctant to add new features related to it...

My advice would be to download the image manually, so that you can follow the download progress yourself.

**Comment by EDiaos** [comment]
Thank you very much,if download the image manually do myself,I have to manage the cache. I think this is not the best solution.
So,I had changed UriLoader to add a method，and add GifAnimation.cs to project to fix using progress in Animation.
If you can merge code to the project, and I think it can help more people

 private static async Task DownloadToCacheFileAsync(Uri uri, string fileName,Action<int> progress)
        {
            try
            {
                using (var client = new Windows.Web.Http.HttpClient())
                {
                    var requestAsync = client.GetAsync(uri);
                    requestAsync.Progress += (i, p) =>
                    {
                        if (null!= progress)
                        {
                            if (p.TotalBytesToReceive!=0&&p.TotalBytesToReceive!=null)
                            {
                                progress((int)((p.BytesReceived * 100) / p.TotalBytesToReceive));
                            }
                        }
                    };
                    using (var message = await requestAsync)
                    {
                        using (var fileStream = await CreateTempFileStreamAsync(fileName))
                        {
                            using (var responseStream = await message.Content.ReadAsInputStreamAsync())
                            {
                                await responseStream.AsStreamForRead().CopyToAsync(fileStream);
                            }
                        }
                    }
                }
            }
            catch
            {
                await DeleteTempFileAsync(fileName);
                throw;
            }
        }

**Comment by thomaslevesque** [comment]
> If you can merge code to the project, and I think it can help more people

It's not that simple... in your case it works because you included the code directly in your project, but UriLoader is not part of the public API, so there would be no way to access it from client code.

I see that there is a `DownloadProgress` event in the `BitmapImage` class, so perhaps it would make sense to add one to `AnimationBehavior`; maybe I'll add it at some point.

**Comment by thomaslevesque** [comment]
Implemented in 1.0.9
