### ISSUE TITLE
some image not working in XamlAnimatedGif

### ISSUE THREAD

**Issue by EDiaos** [XamlAnimatedGif/XamlAnimatedGif#29]
I found this gif not working well in XamlAnimatedGif
http://ww1.sinaimg.cn/large/a6c17c09gw1ertpqt57btg20go08cnpu.gif

I don't know how to fix it,can you help me,Thank you very much

**Comment by thomaslevesque** [comment]
The problem is that this GIF uses an unknown value for the frame's disposal method. According to [the spec](http://www.w3.org/Graphics/GIF/spec-gif89a.txt), there are 4 values defined:

> iv) Disposal Method - Indicates the way in which the graphic is to
> be treated after being displayed.

> Values :    0 -   No disposal specified. The decoder is
>                   not required to take any action.
>             1 -   Do not dispose. The graphic is to be left
>                   in place.
>             2 -   Restore to background color. The area used by the
>                   graphic must be restored to the background color.
>             3 -   Restore to previous. The decoder is required to
>                   restore the area overwritten by the graphic with
>                   what was there prior to rendering the graphic.
>          4-7 -    To be defined.

And this GIF uses the value 5, which is "to be defined".

It seems to work if I handle it the same way as for the value 0, so I'll do that. However there might be images for which it won't work...

**Comment by EDiaos** [comment]
Many thanks for your contribution, I think it will be better and better.

**Comment by thomaslevesque** [comment]
Fixed in 1.0.4
