### ISSUE TITLE
Add Rewind method to Animator class

### ISSUE THREAD

**Issue by jaybp** [XamlAnimatedGif/XamlAnimatedGif#33]
_(original title was **Missing GotoFrame() in Animator class**)_

This option was present in the WpfAnimatedGif and is missing here.
It allowed to set the GIF to a specific frame.

**Comment by thomaslevesque** [comment]
Yes, I know... This feature is pretty difficult to implement, because each frame might depend on the previous frame, so I can't just directly jump to frame X, I have to render the previous frames as well, and rendering frames takes time, especially for large images. WpfAnimatedGif didn't have this problem, because all the frames were fully rendered in advance, so I just had to display them.

I'll try to give it a try someday, but it's not high on my priority list, because I suspect most people don't need it.

**Comment by jaybp** [comment]
Is there a way to reset it to the initial frame. I'm looking for a way to reset the GIF to play from the beginning after its paused (but not complete).

**Comment by thomaslevesque** [comment]
Currently the only way is to clear the SourceUri and set it again.

However it would probably not be too hard to implement a real "Rewind" method, since the first frame never depends on another frame. If you want to try to do it yourself, I'll be glad to accept a PR ;)

**Comment by jaybp** [comment]
Ok, thank you. Will try and implement a reset function.

**Comment by matteocontrini** [comment]
I'm interested in the `Reset`/`Rewind` method as well. Thanks for the "workaround"

**Comment by thomaslevesque** [comment]
Implemented in 1.0.8
