### ISSUE TITLE
Start animator in XamlAnimatedGif.AnimationBehavior.Loaded event not work

### ISSUE THREAD

**Issue by fpsqdb** [XamlAnimatedGif/XamlAnimatedGif#37]
I set XamlAnimatedGif.AnimationBehavior.SetAutoStart(image, false) for an image and register XamlAnimatedGif.AnimationBehavior.Loaded envent, In the loaded event i add following code:
var animator = XamlAnimatedGif.AnimationBehavior.GetAnimator(image);
animator?.Play();

The problem is the animation is not start and the image show nothing, just a black screen(my background is black)

**Comment by thomaslevesque** [comment]
Is the `Loaded` event triggered? Does `GetAnimator` return something?

**Comment by thomaslevesque** [comment]
OK, I reproduced the problem. Not sure what's going on yet, but I'm looking into it

**Comment by thomaslevesque** [comment]
Oh I see... When `AutoStart` is false, the first frame is displayed, but I don't wait until it's fully rendered before raising the `Loaded` event. So when `Loaded` is raised, the first frame is still being rendered, so when `Play` is called, there are 2 tasks working on rendering the first frame. Since there is only one stream, it messes everything up...

**Comment by thomaslevesque** [comment]
I just published a new version that should fix the problem
