### ISSUE TITLE
Support for progressive jpeg files

### ISSUE THREAD

**Issue by macqm** [XamlAnimatedGif/XamlAnimatedGif#43]
Are you planning to add support to pjpeg? I'd really want it in my app. The API I am consuming returns many .gif files in this particular format, with 'image/pjpeg' in content header.

Right now, 'image/pjpeg' files, which should be animated, remain static when using your control.

I'd be happy to help to bring this feature. Do you have an idea what it would take to add the support for progressive jpeg?

**Comment by thomaslevesque** [comment]
> The API I am consuming returns many .gif files in this particular format, with 'image/pjpeg' in content header.

That looks like a bug in the API you're using... "image/pjpeg" is for "Progressive JPEG", which is not an animated format. It just means that the image can be rendered progressively so that you can see a lower quality version of it before it's fully loaded. It's similar to interlacing in GIF images. In any case, a GIF image should definitely not have the "image/pjpeg" content type.

That being said, if the image is actually a GIF and not a Progressive JPEG, it should work fine. The library doesn't look at the MIME type; it just tries to read the image as a GIF, and if it's not a GIF, it displays a static image.
