### ISSUE TITLE
Cache frames

### ISSUE THREAD

**Issue by fpsqdb** [XamlAnimatedGif/XamlAnimatedGif#45]
Would you please provide an option to cache all the frames of an image? It have a poor CPU performance in ARM(windows phone) device when prepare next frame each time. i know, it will increase the memory usage, but make a property to switch between on and off will be better.

**Comment by thomaslevesque** [comment]
The problem is that the images that take a long time to render are usually also the ones that would use a lot of memory... so doing this would just trade one problem for another. But I realize it might be desirable in some scenarios. I can't promise anything, but I'll try to see what can be done. I'll need to do some profiling to see exactly what is taking too long (the decompression or the rendering itself). If it's the decompression, as I expect, then I can just cache the decompressed index stream. If it's the rendering, I'll have to cache the whole pixel array, which is going to use much more memory...

**Comment by ychsue** [comment]
Thanks for your code, it is very nice.
Because I need to get the WriteableBitmaps with Delay times of a Gif file, I wrote a method for _AnimationBehavior_ as shown below to store those information. Oh, you still need to change some other stuffs in this code before it can run.
This way may not be an efficient one, but it works for me. ^_^

 >public static async Task<List&lt;ForAniGIF&gt;> GetFramesAsync(Uri uri)
        {
            //* [2016-12-28 11:05] Get the stream
            var progress = new Progress&lt;int&gt;(percentage => OnDownloadProgress(null, percentage));
            var stream = await (new UriLoader()).GetStreamFromUriAsync(uri, progress);
            //* [2016-12-28 11:13] Get the metaData
            var metaData = await GifDataStream.ReadAsync(stream);
            //* [2016-12-28 11:17] Create a new Animator
            var animator = new ImageAnimator(stream, uri, metaData, null, null);
            //* [2016-12-28 11:28] Get all frames
            List&lt;ForAniGIF&gt; frames = new List&lt;ForAniGIF&gt;();
            for (int i0 = 0; i0 < metaData.Frames.Count; i0++)
            {
                ForAniGIF frame = new ForAniGIF();
                frame.bImg = Animator.CreateBitmap(metaData);
                frame.msDelay = Animator.GetFrameDelay(metaData.Frames[i0]).Milliseconds;
                var targetBitmap = frame.bImg;
                await animator.RenderFrameAsync(i0, System.Threading.CancellationToken.None);
                animator.Bitmap.PixelBuffer.ToArray().CopyTo(targetBitmap.PixelBuffer);
                frames.Add(frame);
            }
            //* [2016-12-28 11:15] Dispose the stream
            animator.Dispose();
            return frames;
        }

**Comment by thomaslevesque** [comment]
@ychsue what you're doing is (more or less) what my previous library WpfAnimatedGif was doing. It works, but it uses a LOT of memory, especially for large images, and is the main reason why I chose a different approach for XamlAnimatedGif.

**Comment by ychsue** [comment]
You are right. But in my case for about 8 small gifs will kill the performance, the App will be frozen. Hm... The two sides of the balance. -_-

**Comment by ychsue** [comment]
Ok. the case for 8 gifs works fine on my Win10  App now. The problem is that the WriteableBitmap object is located in the UI thread. Oh man, that why it consumed almost all the performance when there are more and more cards shown on my App. 
Although GPU is better than CPU for this case, anyway, it works.^_^
The way I solved this problem is by adding something into Animator.cs
1. Declare a byte array & store the UI Thread by

> #if WINRT
        Windows.UI.Core.CoreWindow uiThread = Windows.UI.Core.CoreWindow.GetForCurrentThread();
#endif
        internal byte[] BitmapBytes;

2. Open a new Thread by 
>#if WINRT
            await Task.Run(async () =>
            {
#endif

covering the whole while loop in 'RunAsync()' at about Line 148.

3. Changing all CopyToBitmap & CopyFromBitmap to be CopyToBitmapBytes and CopyFromBitmapBytes.

4. Making some small changes like 'uiThread.Dispatcher.RunAsync' to make them can transfer data.

5. Finally, remember to call 'CopyToBitmap' to copy that BitmapBytes back to _bitmap.

Then, it works. ^_^
Hope this is useful for you.

**Comment by thomaslevesque** [comment]
Thanks for the update @ychsue, hopefully I can use this to improve the library!

**Comment by ychsue** [comment]
Your package saves me a lot of energy so this is a feedback. Hope it can help someone likes me. ^_^

**Comment by thomaslevesque** [comment]
This has been implemented in [2.1.0](https://github.com/XamlAnimatedGif/XamlAnimatedGif/releases/tag/2.1.0) (PR #175)
