### ISSUE TITLE
Image with extraneous byte between blocks can't be displayed

### ISSUE THREAD

**Issue by zhang2ding** [XamlAnimatedGif/XamlAnimatedGif#98]
Thank you for sharing WpfAnimatedGif and XamlAnimatedGif.
I really like them, especially XamlAnimatedGif, which is very good at saving memory.
But I got a question.
I can't animate the image below using XamlAnimatedGif. But WpfAnimatedGif works.
How do you explain?

![cat](https://cloud.githubusercontent.com/assets/16634628/25439416/fc7ccb10-2ace-11e7-8804-51fe9f9396d0.GIF)

Another question:
why Animator doesn't have a method to SEEK the animation to the specified frame index? like ImageAnimationController.GotoFrame(int index) in WpfAnimatedGif.

**Comment by zhang2ding** [comment]
Glad to hear that.
In addition, I suggest adding a method of Animator to SEEK the animation to the specified frame index.

**Comment by thomaslevesque** [comment]
OK, the issue is a bit more subtle than I thought. A fix that just ignores the extraneous byte would be easy enough to implement, but it might not be the right approach. The 2 GIF specifications are quite specific about this, but they disagree with each other...

According to the [GIF87 spec](https://www.w3.org/Graphics/GIF/spec-gif87.txt), extraneous bytes between blocks should be ignored:

>   Any characters encountered between the end of a previous image  and the image separator character are to be ignored.

But the more recent GIF89a spec is stricter, and specifically says the image should be considered corrupt (emphasis mine):

> The Graphics Interchange Format(sm) as specified here should be considered
complete; **any deviation from it should be considered invalid**, including but not
limited to, the use of reserved or undefined fields within control or data
blocks, **the inclusion of extraneous data within or between blocks**, the use of
methods or algorithms not specifically listed as part of the format, etc. In
general, **any and all deviations, extensions or modifications not specified in
this document should be considered to be in violation of the format** and should
be avoided.

A possible approach would be to allow extraneous bytes in GIF87 files, but not in GIF89a files. However, the file you're having trouble with says it follows GIF89a, so it wouldn't help in your case.

I think I'm going to follow the same approach as in [Firefox](https://dxr.mozilla.org/mozilla-esr10/source/image/decoders/nsGIFDecoder2.cpp#789-805) and [Chrome](https://chromium.googlesource.com/chromium/blink.git/+/master/Source/platform/image-decoders/gif/GIFImageReader.cpp#499), which is:
- if extraneous data is found between blocks:
  - if some frames have already been successfully decoded, just assume that we reached the end of the file
  - otherwise, throw an error

This will cause your image to render properly, as it does in all major browsers.

> In addition, I suggest adding a method of Animator to SEEK the animation to the specified frame index.

Could you please open another issue about this?

To be honest, I'm not sure I'll do it; it's not as easy as it seems, because some frames contain only part of the image and must be combined with the previously rendered frame. This means that in order to render a given frame, sometimes it's necessary to render all the previous frames as well, which is costly.

**Comment by thomaslevesque** [comment]
This is fixed in 1.1.9
